// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "bfb432e2-6a8b-4a1e-be88-f2bc126bf4e1");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1769722890);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1769722890);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "ccfc6aec-a6f3-4291-a6ec-607fb7a527c1");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1769722887);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 163);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-treatment-a-callout-badge-rollout-v2:treatment-a-callout-badge");
user_pref("browser.newtabpage.activity-stream.impressionId", "{3bf6996c-c1cd-484e-b0a4-577305947c40}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1769722888);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1769722891002");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1769744491002");
user_pref("browser.search.region", "BR");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1769722889);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1769722888);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 6);
user_pref("captchadetection.lastSubmission", 1769722);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "338e2eb9-61f3-45b4-8998-47a8c9edfeaf");
user_pref("datareporting.dau.cachedUsageProfileID", "50b10313-c157-4562-9427-f4dfc7a8a803");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1769722889069");
user_pref("distribution.iniFile.exists.appversion", "147.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "BR");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "968fa92914a2434d9b4e9146b5a8a02e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.cache.lastUpdate", 1769722887);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260128224941");
user_pref("extensions.lastAppVersion", "147.0.2");
user_pref("extensions.lastPlatformVersion", "147.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_interventions", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"ee78aa39-e9f2-49a4-b327-e33c7ba61576\",\"formautofill@mozilla.org\":\"fc9b7e85-4a30-4572-9b78-d38936f05fb3\",\"ipp-activator@mozilla.com\":\"3fce0b70-31e6-4667-b97b-f782e413f4b8\",\"pictureinpicture@mozilla.org\":\"13b34f83-7c51-4fc5-bd6b-4ea9b4e15569\",\"addons-search-detection@mozilla.com\":\"ac14b695-fe91-427b-8c28-81d41547997a\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"c125ef82-1d5e-4e22-9262-a2a5e4e2c23f\",\"default-theme@mozilla.org\":\"01a99633-fe76-44f6-89ea-be66329f77d4\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "3ce2e156-d1ec-4ad4-a394-804ec7b2245d");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("privacy.trackingprotection.allow_list.hasUserInteractedWithETPSettings", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("toolkit.profiles.storeID", "b9a42728");
user_pref("toolkit.startup.last_success", 1769722885);
user_pref("toolkit.telemetry.cachedClientID", "05fa8d82-d610-41ab-9972-a1746895755d");
user_pref("toolkit.telemetry.cachedProfileGroupID", "31ab9f9c-b1fe-4a08-8161-b366600615b7");
user_pref("toolkit.telemetry.previousBuildID", "20260128224941");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
